trigger:
- main
- cucumber-reports

pool:
  vmImage: 'windows-latest'

steps:
  #- task: NodeTool@0
  #  inputs:
  #    versionSpec: '14.x'
  #  displayName: 'Install Node.js'
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - task: Maven@4
    displayName: 'Maven Tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
        # '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    continueOnError: true

  #- task: PublishTestResults@2
  #  displayName: 'Publish Cucumber Reports'
  #  inputs:
  #    testRunner: 'JUnit'
  #    testResultsFiles: '**/cucumber-reports/Cucumber.json'
  #    publishRunAttachments: true
  #    searchFolder: '**/cucumber-reports/*.json'
  #  continueOnError: true
