trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Maven@3
    inputs:
      goals: 'test'
      publishJUnitResults: true
      testResultsFiles: './target/cucumber-reports/Cucumber.json'
      codeCoverageToolOption: 'None'
    displayName: 'Maven package'

  - task: PublishTestResults@2
    inputs:
      jsonDir: '$(System.DefaultWorkingDirectory)/target/surefire-reports'
      outputPath: './target/cucumber-reports'
      testResultsFiles: '*.json'
      testRunTitle: 'Test Results'
      name: 'Test Results'
      title: API
    displayName: 'Publish Cucumber Reports'