trigger:
- main
- cucumber-reports

pool:
  vmImage: 'windows-latest'

steps:
  #- task: NodeTool@0
  #  inputs:
  #    versionSpec: '14.x'
  #  displayName: 'Install Node.js'

  - task: Maven@3
    displayName: 'Maven Tests'
    inputs:
      goals: 'test'
      #publishJUnitResults: true
      #testResultsFiles: |
      #  $(System.DefaultWorkingDirectory)/**/*.json
      #  $(System.DefaultWorkingDirectory)/**/TEST-*.xml
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Cucumber Reports'
    inputs:
      testResultsFiles: |
        $(System.DefaultWorkingDirectory)/test-results/**/TEST-*.xml
        $(System.DefaultWorkingDirectory)/test-results/**/*.json
      publishRunAttachments: true
      searchFolder: '$(System.DefaultWorkingDirectory)/test-results/**/'
      continueOnError: true
